root@lux:/var/www/lux-marketing# # On VPS - Check the most recent error
journalctl -u lux-marketing.service -n 100 --no-pager | grep -A 20 "Error\|Traceback" | tail -50
Oct 21 07:07:06 lux systemd[1]: lux-marketing.service: Main process exited, code=exited, status=1/FAILURE
Oct 21 07:07:06 lux systemd[1]: lux-marketing.service: Failed with result 'exit-code'.
Oct 21 07:07:16 lux systemd[1]: lux-marketing.service: Scheduled restart job, restart counter is at 7.
Oct 21 07:07:16 lux systemd[1]: Stopped lux-marketing.service - LUX Marketing Automation Platform.
Oct 21 07:07:16 lux systemd[1]: Started lux-marketing.service - LUX Marketing Automation Platform.
Oct 21 07:07:17 lux gunicorn[940]: Traceback (most recent call last):
Oct 21 07:07:17 lux gunicorn[940]:   File "/var/www/lux-marketing/venv/bin/gunicorn", line 7, in <module>
Oct 21 07:07:17 lux gunicorn[940]:     sys.exit(run())
Oct 21 07:07:17 lux gunicorn[940]:              ^^^^^
Oct 21 07:07:17 lux gunicorn[940]:   File "/var/www/lux-marketing/venv/lib/python3.11/site-packages/gunicorn/app/wsgiapp.py", line 66, in run
Oct 21 07:07:17 lux gunicorn[940]:     WSGIApplication("%(prog)s [OPTIONS] [APP_MODULE]", prog=prog).run()
Oct 21 07:07:17 lux gunicorn[940]:   File "/var/www/lux-marketing/venv/lib/python3.11/site-packages/gunicorn/app/base.py", line 235, in run
Oct 21 07:07:17 lux gunicorn[940]:     super().run()
Oct 21 07:07:17 lux gunicorn[940]:   File "/var/www/lux-marketing/venv/lib/python3.11/site-packages/gunicorn/app/base.py", line 71, in run
Oct 21 07:07:17 lux gunicorn[940]:     Arbiter(self).run()
Oct 21 07:07:17 lux gunicorn[940]:     ^^^^^^^^^^^^^
Oct 21 07:07:17 lux gunicorn[940]:   File "/var/www/lux-marketing/venv/lib/python3.11/site-packages/gunicorn/arbiter.py", line 57, in __init__
Oct 21 07:07:17 lux gunicorn[940]:     self.setup(app)
Oct 21 07:07:17 lux gunicorn[940]:   File "/var/www/lux-marketing/venv/lib/python3.11/site-packages/gunicorn/arbiter.py", line 117, in setup
Oct 21 07:07:17 lux gunicorn[940]:     self.app.wsgi()
Oct 21 07:07:17 lux gunicorn[940]:   File "/var/www/lux-marketing/venv/lib/python3.11/site-packages/gunicorn/app/base.py", line 66, in wsgi
Oct 21 07:07:17 lux gunicorn[940]:     self.callable = self.load()
Oct 21 07:07:17 lux gunicorn[940]:                     ^^^^^^^^^^^
Oct 21 07:07:17 lux gunicorn[940]:   File "/var/www/lux-marketing/venv/lib/python3.11/site-packages/gunicorn/app/wsgiapp.py", line 57, in load
Oct 21 07:07:17 lux gunicorn[940]:     return self.load_wsgiapp()
Oct 21 07:07:17 lux gunicorn[940]:            ^^^^^^^^^^^^^^^^^^^
--
Oct 21 07:07:17 lux gunicorn[940]: SyntaxError: unexpected character after line continuation character
Oct 21 07:07:17 lux systemd[1]: lux-marketing.service: Main process exited, code=exited, status=1/FAILURE
Oct 21 07:07:17 lux systemd[1]: lux-marketing.service: Failed with result 'exit-code'.
Oct 21 07:07:27 lux systemd[1]: lux-marketing.service: Scheduled restart job, restart counter is at 8.
Oct 21 07:07:27 lux systemd[1]: Stopped lux-marketing.service - LUX Marketing Automation Platform.
Oct 21 07:07:27 lux systemd[1]: Started lux-marketing.service - LUX Marketing Automation Platform.
Oct 21 07:07:28 lux gunicorn[946]: INFO:ai_agent:LUX AI Agent initialized successfully
Oct 21 07:07:29 lux gunicorn[946]: DEBUG:tzlocal:/etc/timezone found, contents:
Oct 21 07:07:29 lux gunicorn[946]:  Etc/UTC
Oct 21 07:07:29 lux gunicorn[946]: DEBUG:tzlocal:/etc/localtime found
Oct 21 07:07:29 lux gunicorn[946]: DEBUG:tzlocal:2 found:
Oct 21 07:07:29 lux gunicorn[946]:  {'/etc/timezone': 'Etc/UTC', '/etc/localtime is a symlink to': 'Etc/UTC'}
Oct 21 07:07:29 lux gunicorn[946]: INFO:apscheduler.scheduler:Scheduler started
Oct 21 07:07:29 lux gunicorn[946]: DEBUG:apscheduler.scheduler:Looking for jobs to run
Oct 21 07:07:29 lux gunicorn[946]: INFO:scheduler:Email scheduler initialized
Oct 21 07:07:29 lux gunicorn[946]: DEBUG:apscheduler.scheduler:No jobs; waiting until a job is added
Oct 21 07:08:28 lux systemd[1]: Stopping lux-marketing.service - LUX Marketing Automation Platform...
Oct 21 07:08:29 lux systemd[1]: lux-marketing.service: Deactivated successfully.
Oct 21 07:08:29 lux systemd[1]: Stopped lux-marketing.service - LUX Marketing Automation Platform.
Oct 21 07:08:29 lux systemd[1]: lux-marketing.service: Consumed 3.045s CPU time.
Oct 21 07:08:29 lux systemd[1]: Started lux-marketing.service - LUX Marketing Automation Platform.
--
Oct 21 07:09:36 lux gunicorn[993]: ERROR:routes:Error in LUX campaign generation: 'LUXAgent' object has no attribute 'generate_campaign_content'